[package]
name = "rh-history"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"  # Optimization to reduce size
lto = true       # Link Time Optimization 
codegen-units = 1  # Combining code units to improve optimization

[dependencies]
dirs = "6.0.0"
skim = "0.17.3"
